/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myset.exercise

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

class MySetTest {
    @Test
    fun `isEmpty returns true when empty`() {
        val mySet = MySet()
        val result = mySet.isEmpty()
        assertTrue(result)
    }
    @Test
    fun `isEmpty returns false when not empty`() {
        val mySet = MySet()
        mySet.add("a")
        val result = mySet.isEmpty()
        assertFalse(result)
    }
    @Test
    fun `size returns 0 for empty set`() {
        val mySet = MySet()
        val result = mySet.size
        assertEquals(0, result)
    }
    @Test
    fun `size returns 1 for set with 1 element`() {
        val mySet = MySet()
        mySet.add("a")

        val result = mySet.size

        assertEquals(1, result)
    }
    @Test
    fun `contains a returns true for set with a element`() {
        val mySet = MySet()
        mySet.add("a")

        val result = mySet.contains("a")

        assertTrue(result)
    }
    @Test
    fun `contains a returns false empty set`() {
        val mySet = MySet()
        val result = mySet.contains("a")
        assertFalse(result)
    }
    @Test
    fun `contains a returns false for a nonempty set without an a element`() {
        val mySet = MySet()
        mySet.add("b")

        val result = mySet.contains("a")

        assertFalse(result)
    }
}
