/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myset.exercise

import kotlin.test.Test
import kotlin.test.assertTrue

class MySetTest {
    @Test
    fun `isEmpty returns true when empty`() {
        val mySet = MySet()
        val result = mySet.isEmpty()
        assertTrue(result)
    }
}
