/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myset.exercise

class MySet {
    private var isEmpty = true
    fun isEmpty(): Boolean {
        return isEmpty
    }

    fun add(element: String) {
        isEmpty = false
    }
}
