/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package myset.exercise

class MySet {
    var size = 0
    private set
    var setValue:  Array<String?> = arrayOfNulls(10)
    fun isEmpty(): Boolean {
        return size == 0
    }

    fun add(element: String) {
        setValue[size] = element
        size++
    }

    fun contains(element: String): Boolean {
        for (index in 0 until size) {
            if (setValue[index] == element)
                return true
        }
        return false
    }
}
